---
# image: "docker.elastic.co/elasticsearch/elasticsearch"
# imageTag: "6.3.1"
replicas: 1
minimumMasterNodes: 1

roles:
  master: "true"
  ingest: "true"
  data: "true"
  remote_cluster_client: "false"
# roles:
#   master: "true"
# Shrink default JVM heap.
esJavaOpts: "-Xmx128m -Xms128m"

# Allocate smaller chunks of memory per pod.
resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "1000M"

persistence:
  enabled: false
# Persistant data is disabled as this is just for a Demo

# Request smaller persistent volumes.
# volumeClaimTemplate:
#   accessModes: [ "ReadWriteOnce" ]
#   storageClassName: "standard"
#   resources:
#     requests:
#       storage: 100M
